workspace = { members = [ "editor","examples/*"] }

[package]
name = "pge"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
winit = "0.30"
wgpu = "0.20"
anyhow = "1"
bytemuck = { version = "1.15", features = ["derive"] }
glam = "0.27.0"
ttf-parser = "0.21.1"
lyon = "1.0.1"
thunderdome = "0.6"
image = "0.25"
gltf = "1"