name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose 
    - name: Run Benchmarks
      run: |
        cargo bench
        mkdir -p benchmark-report
        criterion-report-dir=./target/criterion/report
        cp -r $criterion-report-dir/* benchmark-report/
    - name: Upload Benchmark Report
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-report
        path: benchmark-report/